# Build the project
FROM node:20-alpine AS build

WORKDIR /app

# Copy packages
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Build app
RUN npm run build


# Serve the image
FROM nginx:alpine AS final

# Copy the built files to Nginx
COPY --from=build /app/dist /usr/share/nginx/html

# Copy nginx configuration for redirection handling
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Expose HTTP port
EXPOSE 80

# El ENTRYPOINT predeterminado de Nginx ya inicia el servidor
CMD ["nginx", "-g", "daemon off;"]
