FROM node:18-alpine

WORKDIR /usr/src/app

# Copy app Packages
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the source code to the container
# Run directly
# COPY . .
# Run with docker compose
COPY src src

# Expose the application port (same as the docker-compose file)
EXPOSE 5000

# Start the app
CMD [ "node", "src/server.js" ]
